<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="InequalityTest-20160406174321" tests="1" time="0.709">
	<testcase classname="InequalityTest" name="test_IsClassify_1" time="0.709">
		<error message="&quot;[{'type': 1, 'pct': 90, 'id': 500}]&quot; != 500" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 25, in test_IsClassify_1
    self.assertEqual(Actuval, expected)
AssertionError: "[{'type': 1, 'pct': 90, 'id': 500}]" != 500
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[200
[{'type': 1, 'pct': 90, 'id': 500}]
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
