<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="InequalityTest-20160406183203" tests="1" time="0.673">
	<testcase classname="InequalityTest" name="test_IsClassify_1" time="0.673">
		<error message="[{'type': 1, 'pct': 90, 'id': 500}] != 500" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 29, in test_IsClassify_1
    self.assertEqual(Actuval, expected)
AssertionError: [{'type': 1, 'pct': 90, 'id': 500}] != 500
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[200
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
