<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="InequalityTest-20160406152436" tests="1" time="21.013">
	<testcase classname="InequalityTest" name="test_IsEmail_1" time="21.013">
		<error message="None != 'hi christopher  i was going to be over y[1158 chars]any '" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 31, in test_IsEmail_1
    self.assertEqual(Actuval, expected)
AssertionError: None != 'hi christopher  i was going to be over y[1158 chars]any '
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[failed to connect
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
