<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="InequalityTest-20160406182702" tests="1" time="0.664">
	<testcase classname="InequalityTest" name="test_IsClassify_1" time="0.664">
		<error message="0" type="KeyError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 32, in test_IsClassify_1
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 23, in Ontobi_API
    value = output[0][0]
KeyError: 0
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[200
[{'type': 1, 'id': 500, 'pct': 90}]
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
