<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="InequalityTest-20160406165013" tests="1" time="0.884">
	<testcase classname="InequalityTest" name="test_IsClassify_1" time="0.884">
		<error message="'id'" type="KeyError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 23, in test_IsClassify_1
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 17, in Ontobi_API
    output = str(j["data"]["id"])
KeyError: 'id'
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[200
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
