<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="InequalityTest-20160406175452" tests="1" time="0.723">
	<testcase classname="InequalityTest" name="test_IsClassify_1" time="0.723">
		<error message="list index out of range" type="IndexError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 24, in test_IsClassify_1
    Actuval=self.Ontobi_API(text)
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 17, in Ontobi_API
    output = str(j["data"]["categories"][1])
IndexError: list index out of range
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[200
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
