<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="InequalityTest-20160407182643" tests="1" time="0.692">
	<testcase classname="InequalityTest" name="test_IsClassify_many" time="0.692">
		<error message="500 != '500'" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:/Users/CHRIS/PycharmProjects/Requests/Requests.py", line 36, in test_IsClassify_many
    self.assertEqual(Actuval, catid)
AssertionError: 500 != '500'
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[500
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
